# Generated by Django 3.0.14 on 2021-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Color_Black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Color_Blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Color_Brown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Color_Red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Color_White',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_2XL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_3XL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_Large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_Medium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_Small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_XL',
            field=models.BooleanField(default=False),
        ),
    ]
