# Generated by Django 3.0.14 on 2021-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211204_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color_Black',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color_Blue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color_Brown',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color_Red',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color_White',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_2XL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_3XL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_Large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_Medium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_Small',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_XL',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('brown', 'Brown'), ('white', 'White')], default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XLarge'), ('2xl', '2XL'), ('3xl', '3XL')], default='large', max_length=10),
        ),
    ]
